export const NEW_COMMENT_REQUEST = "NEW_COMMENT_REQUEST";
export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";
export const NEW_COMMENT_FAIL = "NEW_COMMENT_FAIL";
export const NEW_COMMENT_RESET = "NEW_COMMENT_RESET";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
