export const ADD_VIDEO_LIKE_DISLIKE_REQUEST = "ADD_VIDEO_LIKE_DISLIKE_REQUEST";
export const ADD_VIDEO_LIKE_DISLIKE_SUCCESS = "ADD_VIDEO_LIKE_DISLIKE_SUCCESS";
export const ADD_VIDEO_LIKE_DISLIKE_FAIL = "ADD_VIDEO_LIKE_DISLIKE_FAIL";
export const ADD_VIDEO_LIKE_DISLIKE_RESET = "ADD_VIDEO_LIKE_DISLIKE_RESET";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
