export const ADD_VIDEO_LIKE_DISLIKE_REQUEST = "ADD_VIDEO_LIKE_DISLIKE_REQUEST";
export const ADD_VIDEO_LIKE_DISLIKE_SUCCESS = "ADD_VIDEO_LIKE_DISLIKE_SUCCESS";
export const ADD_VIDEO_LIKE_DISLIKE_FAIL = "ADD_VIDEO_LIKE_DISLIKE_FAIL";
export const ADD_VIDEO_LIKE_DISLIKE_RESET = "ADD_VIDEO_LIKE_DISLIKE_RESET";



export const GET_LIKED_VIDEOS_REQUEST = "GET_LIKED_VIDEOS_REQUEST";
export const GET_LIKED_VIDEOS_SUCCESS = "GET_LIKED_VIDEOS_SUCCESS";
export const GET_LIKED_VIDEOS_FAIL = "GET_LIKED_VIDEOS_FAIL";





export const CLEAR_ERRORS = "CLEAR_ERRORS";
