export const CREATE_SUBSCRIBER_REQUEST = "CREATE_SUBSCRIBER_REQUEST";
export const CREATE_SUBSCRIBER_SUCCESS = "CREATE_SUBSCRIBER_SUCCESS";
export const CREATE_SUBSCRIBER_FAIL = "CREATE_SUBSCRIBER_FAIL";
export const CREATE_SUBSCRIBER_RESET = "CREATE_SUBSCRIBER_RESET";

export const DELETE_SUBSCRIBER_REQUEST = "DELETE_SUBSCRIBER_REQUEST";
export const DELETE_SUBSCRIBER_SUCCESS = "DELETE_SUBSCRIBER_SUCCESS";
export const DELETE_SUBSCRIBER_FAIL = "DELETE_SUBSCRIBER_FAIL";
export const DELETE_SUBSCRIBER_RESET = "DELETE_SUBSCRIBER_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
