export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST'
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS'
export const FORGET_PASSWORD_FAIL = 'FORGET_PASSWORD_FAIL'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'


export const RESET_PASSWORD_FOR_LOGGEDUSER_REQUEST = 'RESET_PASSWORD_FOR_LOGGEDUSER_REQUEST'
export const RESET_PASSWORD_FOR_LOGGEDUSER_SUCCESS = 'RESET_PASSWORD_FOR_LOGGEDUSER_SUCCESS'
export const RESET_PASSWORD_FOR_LOGGEDUSER_FAIL = 'RESET_PASSWORD_FOR_LOGGEDUSER_FAIL'

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const GET_USERPROFILE_REQUEST = "GET_USERPROFILE_REQUEST";
export const GET_USERPROFILE_SUCCESS = "GET_USERPROFILE_SUCCESS";
export const GET_USERPROFILE_FAIL = "GET_USERPROFILE_FAIL";
export const GET_USERPROFILE_RESET = "GET_USERPROFILE_RESET";


export const GET_USER_WATCH_HISTORY_REQUEST = "GET_USER_WATCH_HISTORY_REQUEST";
export const GET_USER_WATCH_HISTORY_SUCCESS = "GET_USER_WATCH_HISTORY_SUCCESS";
export const GET_USER_WATCH_HISTORY_FAIL = "GET_USER_WATCH_HISTORY_FAIL";
export const GET_USER_WATCH_HISTORY_RESET = "GET_USER_WATCH_HISTORY_RESET";

export const UPDATE_COVER_IMAGE_REQUEST = "UPDATE_COVER_IMAGE_REQUEST";
export const UPDATE_COVER_IMAGE_SUCCESS = "UPDATE_COVER_IMAGE_SUCCESS";
export const UPDATE_COVER_IMAGE_FAIL = "UPDATE_COVER_IMAGE_FAIL";

export const UPDATE_AVATAR_IMAGE_REQUEST = "UPDATE_AVATAR_IMAGE_REQUEST";
export const UPDATE_AVATAR_IMAGE_SUCCESS = "UPDATE_AVATAR_IMAGE_SUCCESS";
export const UPDATE_AVATAR_IMAGE_FAIL = "UPDATE_AVATAR_IMAGE_FAIL";

export const GOOGLE_AUTH_REQUEST = "GOOGLE_AUTH_REQUEST";
export const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
export const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL";


export const GET_USER_VIDEO_RECOMMENDATIONS_REQUEST = "GET_USER_VIDEO_RECOMMENDATIONS_REQUEST";
export const GET_USER_VIDEO_RECOMMENDATIONS_SUCCESS = "GET_USER_VIDEO_RECOMMENDATIONS_SUCCESS";
export const GET_USER_VIDEO_RECOMMENDATIONS_FAIL = "GET_USER_VIDEO_RECOMMENDATIONS_FAIL";
export const GET_USER_VIDEO_RECOMMENDATIONS_RESET = "GET_USER_VIDEO_RECOMMENDATIONS_RESET";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
