
export const VIDEO_UPLOAD_REQUEST = "VIDEO_UPLOAD_REQUEST";
export const VIDEO_UPLOAD_SUCCESS = "VIDEO_UPLOAD_SUCCESS";
export const VIDEO_UPLOAD_FAIL = "VIDEO_UPLOAD_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";


export const VIDEO_FETCHED_REQUEST = 'VIDEO_FETCHED_REQUEST'
export const VIDEO_FETCHED_SUCCESS = 'VIDEO_FETCHED_SUCCESS'
export const VIDEO_FETCHED_FAIL = 'VIDEO_FETCHED_FAIL'
 
export const VIDEO_FETCHED_RESET = 'VIDEO_FETCHED_RESET'
 