export const VIDEO_UPLOAD_REQUEST = "VIDEO_UPLOAD_REQUEST";
export const VIDEO_UPLOAD_SUCCESS = "VIDEO_UPLOAD_SUCCESS";
export const VIDEO_UPLOAD_FAIL = "VIDEO_UPLOAD_FAIL";

export const VIDEO_FETCHED_REQUEST = "VIDEO_FETCHED_REQUEST";
export const VIDEO_FETCHED_SUCCESS = "VIDEO_FETCHED_SUCCESS";
export const VIDEO_FETCHED_FAIL = "VIDEO_FETCHED_FAIL";
export const VIDEO_FETCHED_RESET = "VIDEO_FETCHED_RESET";

export const VIDEO_DETAILS_REQUEST = "VIDEO_DETAILS_REQUEST";
export const VIDEO_DETAILS_SUCCESS = "VIDEO_DETAILS_SUCCESS";
export const VIDEO_DETAILS_FAIL = "VIDEO_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
